emb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home'))
]

home/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about_us, name='about'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('portfolio/portfolio-item/<int:pk>', views.portfolio_item, name='portfolio_item'),
    path('services/', views.services, name='services'),
]

urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.core.exceptions import ValidationError
from tinymce.models import HTMLField


class Content(models.Model):
    name = models.CharField('Name', max_length=7, default='Content', help_text='Leave it as it is.',
                            blank=True, null=True)
    about_par_1 = HTMLField('About Info Paragraph 1', help_text='About page first paragraph',
                                         blank=True, null=True)
    city_country = models.CharField('City, Country', max_length=50, help_text='City, Country (Address)',
                                    blank=True, null=True)
    address = models.CharField('Street Number, Name, other', max_length=75, blank=True, null=True)
    email = models.EmailField('Your Email', help_text='Your email for contact info', blank=True, null=True)
    phone_1 = models.CharField('Telephone', max_length=20, help_text='Your phone for contact info. Do the '
                                                                     'formatting here (e.g. +1 (438) 777 7777',
                               blank=True, null=True)
    phone_2 = models.CharField('Telephone', max_length=20, help_text='Your Second phone for contact info. Do the '
                                                                     'formatting here (e.g. +1 (438) 777 7777)',
                               blank=True, null=True)
    intro_text = models.TextField('Intro Text', help_text="Text underneath 'Kane'",
                                  blank=True, null=True)
    services_text = models.TextField('Text for services', help_text="Text underneath 'Services' (home page)",
                                     blank=True, null=True)
    latest_projects_text = models.TextField('Text for latest projects', help_text="Text underneath 'Latest Projects'"
                                                                                  " (home page)", blank=True, null=True)
    twitter_link = models.URLField('Twitter Link', help_text='Contact info', null=True, blank=True)
    spotify_link = models.URLField('Spotify Link', help_text='Contact info', null=True, blank=True)
    fb_link = models.URLField('Facebook Link', help_text='Contact Info', blank=True, null=True)
    ig_link = models.URLField('Instagram Link', help_text='Contact Info', blank=True, null=True)
    linkedin_link = models.URLField('LinkedIn Link', help_text='Contact Info', blank=True, null=True)
    footer_desc_par_1 = models.TextField('Footer Short Description 1', help_text='Paragraph 1, Max one sentence',
                                         max_length=500, blank=True, null=True)
    hide_info = models.BooleanField('Hide all info', help_text='Hide all information', default=False)

    def __str__(self):
        return "Content"

    def clean(self):
        if self.pk is None and len(Content.objects.all()) >= 1:
            raise ValidationError('You are NOT allowed to create more than one content!')

    class Meta:
        verbose_name = 'Content'
        verbose_name_plural = 'Content'


class Inquiry(models.Model):
    inquiry_date = models.DateTimeField(null=True)
    name = models.CharField('Name', max_length=40)
    email = models.EmailField()
    subject = models.CharField('Subject', max_length=30)
    service = models.CharField('Service Type', max_length=30)
    budget = models.CharField('Budget', max_length=20, blank=True, null=True)
    message = models.TextField('Message')
    notes = models.TextField('Personal Notes', blank=True, null=True)

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'Inquiry'
        verbose_name_plural = 'Inquiries'
        ordering = ['-inquiry_date']


class Services(models.Model):
    service_name = models.CharField('Service Name', primary_key=True, max_length=30,
                                    help_text='Name of the service you provide')
    short_description = HTMLField('Short Description', help_text='Short Description')
    description = HTMLField('Description', help_text='Detailed Description')
    icon = models.FileField('Icon', upload_to='photos/services/', help_text='MUST BE .SVG EXTENSIONS',
                            blank=False, null=False)
    main_img = models.ImageField('Main Img', upload_to='photos/services/')
    hide = models.BooleanField('Hide Service', help_text='Check to hide service', default=False)

    def __str__(self):
        return self.service_name

    class Meta:
        verbose_name = 'Service'
        verbose_name_plural = 'Services'


class PortfolioItem(models.Model):
    title = models.CharField('Project Name', max_length=30, help_text='Name of the project')
    date = models.DateField('Date of the Event', help_text='Date when the event took place', blank=True, null=True)
    service_category = models.ForeignKey(Services, max_length=30, help_text='Type of the service',
                                         on_delete=models.CASCADE)
    description_1 = HTMLField('Description, Paragraph 1', help_text='Event Description')
    description_2 = HTMLField('Description, Paragraph 2', help_text='Event Description', blank=True, null=True)
    description_3 = HTMLField('Description, Paragraph 3', help_text='Event Description', blank=True, null=True)
    press_link = models.URLField('Press Link', help_text='Link for Press Article', blank=True, null=True)
    fb_link = models.URLField('Facebook Link', help_text='Facebook Link for More', blank=True, null=True)
    ig_link = models.URLField('Instagram Link', help_text='Instagram Link for More', blank=True, null=True)
    spotify_link = models.URLField('Spotify Link', help_text='Spotify Link', null=True, blank=True)
    twitter_link = models.URLField('Twitter Link', help_text='Twitter Link for More', blank=True, null=True)
    linkedin_link = models.URLField('LinkedIn Link', help_text='LinkedInLink for More', blank=True, null=True)
    hide = models.BooleanField('Hide Item', help_text='Check to hide item', default=False)
    front_image = models.ImageField('Front Image', help_text="Square Image", upload_to='photos/portfolio/', blank=False, null=True)
    img_1 = models.ImageField(upload_to='photos/portfolio/', blank=True, null=True)
    img_2 = models.ImageField(upload_to='photos/portfolio/', blank=True, null=True)
    img_3 = models.ImageField(upload_to='photos/portfolio/', blank=True, null=True)
    img_4 = models.ImageField(upload_to='photos/portfolio/', blank=True, null=True)
    img_5 = models.ImageField(upload_to='photos/portfolio/', blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Portfolio Item'
        verbose_name_plural = 'Portfolio Items'

home/views.py
from django.shortcuts import render, get_list_or_404, redirect
from .models import PortfolioItem, Services, Inquiry, Content
from django.db.models import Q
from django.contrib import messages
from django.core.mail import send_mail
import smtplib
from emb.settings import EMAIL_HOST_USER, REGULAR_EMAIL
import datetime
import pytz


def index(request):
    services = Services.objects.filter(hide=False)
    portfolio_items = PortfolioItem.objects.filter(hide=False).order_by('-date')[:4]
    content = Content.objects.filter(hide_info=False).first()
    year = datetime.datetime.now().year
    context = {
        'services': services,
        'portfolio_items': portfolio_items,
        'content': content,
        'active_page': 'index',
        'year': year
    }
    return render(request, 'home/index.html', context)


def about_us(request):
    content = Content.objects.filter(hide_info=False).first()
    context = {
        'content': content,
        'active_page': 'about'
    }
    return render(request, 'home/about_us.html', context)


def portfolio(request):
    portfolio_items = PortfolioItem.objects.filter(hide=False).order_by('-date')
    services = {item.service_category for item in portfolio_items}
    content = Content.objects.filter(hide_info=False).first()
    context = {
        'portfolio_items': portfolio_items,
        'unique_services': services,
        'content': content,
        'active_page': 'portfolio'
    }
    return render(request, 'home/portfolio.html', context)


def portfolio_item(request, pk):
    portfolio_item = get_list_or_404(PortfolioItem, id=pk, hide=False)
    related_projects = PortfolioItem.objects.filter(~Q(id=pk), service_category=portfolio_item[0].service_category, hide=False)
    content = Content.objects.filter(hide_info=False).first()
    context = {
        'portfolio_item': portfolio_item,
        'related_projects': related_projects,
        'content': content,
        'active_page': 'portfolio'
    }
    return render(request, 'home/portfolio-item.html', context)


def services(request):
    if request.method == 'POST':
        honey_pot = request.POST.get('email_confirm')
        if int(request.session.get('filed_inquiry', 0)) >= 1:
            messages.error(request, 'You have already submitted an inquiry! For more, please, reach out via e-mail.')
        elif honey_pot:
            return redirect('services')  # silently drop spam
        else:
            inquiry_date = datetime.datetime.now(pytz.timezone('US/Eastern'))
            name = request.POST.get('name')
            email = request.POST.get('email')
            subject = request.POST.get('email_subject')
            service = request.POST.get('service_type')
            budget = request.POST.get('budget')
            message = request.POST.get('inquiry')
            inquiry = Inquiry(inquiry_date=inquiry_date, name=name, email=email, subject=subject,
                              service=service, budget=budget, message=message)
            inquiry.save()
            mail_message = f"FROM: {name} <{email}>\nSUBJECT: {subject}\nSERVICE: {service}\nBUDGET: " \
                           f"{budget if budget else 'N/A'}\nMESSAGE: {message}"
            send_mail(
                subject='Please DO NOT Reply, Automated Email',
                message='Thank you for submitting the form, our team will get back to you shortly. \nSincerely,'
                        '\nKTAgency',
                from_email=EMAIL_HOST_USER,
                recipient_list=[email],
                fail_silently=False)
            send_mail(subject=subject,
                      message=mail_message,
                      from_email=EMAIL_HOST_USER,
                      recipient_list=[EMAIL_HOST_USER, REGULAR_EMAIL],
                      fail_silently=False)

            messages.success(request, 'Your form has been submitted successfully!')
            prev_value = int(request.session.get('filed_inquiry', 0))
            request.session['filed_inquiry'] = prev_value + 1

    services = Services.objects.filter(hide=False)[::-1]
    content = Content.objects.filter(hide_info=False).first()
    context = {
        'services': services,
        'content': content,
        'active_page': 'services'
    }
    return render(request, 'home/services.html', context)


handler404 = 'home.'

templates/home/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div id="hero" class="hero overlay">
        <div class="hero-content">
            <div class="hero-text square">
                <h1>K A N E &nbsp; T O W E R</h1>
                {% if content.intro_text %}
                    <p>{{ content.intro_text | safe }}</p>
                {% endif %}
                <a href="#services" class="btn btn-border">Learn more</a>
            </div><!-- /.hero-text -->
        </div><!-- /.hero-content -->
    </div><!-- /.hero -->

    <main id="main" class="site-main">
    <div class="parallax-kane-didot"></div>

        <section class="site-section section-services gray-bg text-center" id="services">
            <div class="container">
                <h2 class="heading-separator">Solutions</h2>
                {% if content.services_text %}
                    <p class="subheading-text">{{ content.services_text | safe}}</p>
                {% endif %}
                <div class="row">
                    {% if services %}
                        {% for service in services %}
                        <div class="col-md-3 col-xs-6 !tw-px-0 sm:tw-px-4">
                            <div class="service">
                                <div class="tw-flex tw-items-center tw-justify-center">
                                    <a href="{% url 'home:services' %}#{{ service.service_name }}-id"><img src="{{ service.icon.url }}" alt="{{ service.service_name }} Icon"></a>
                                </div>
                                <a href="{% url 'home:services' %}#{{ service.service_name }}-id">
                                <h3 class="service-title didot-font !tw-font-bold tw-underline sm:tw-no-underline">{{ service.service_name }}</h3>
                                </a>
                                <div class="tw-flex tw-justify-center tw-mt-8">
                                    <div>
                                        {{ service.short_description | safe }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    {% endif %}
                </div>
                <a href="{% url 'home:services' %}" class="btn mb-10">Learn More</a>
            </div>
        </section><!-- /.section-services -->
        <div class="parallax-kane-flip"></div>


        <section class="site-section section-portfolio">
            <div class="container">
                <div class="text-center">
                    <h2 class="heading-separator">Our Impact</h2>
                    {% if content.latest_projects_text %}
                        <p class="subheading-text">{{ content.latest_projects_text | safe }}</p>
                    {% endif %}
                </div>
                <div class="row">
                    {% if portfolio_items %}
                        {% for portfolio_item in portfolio_items %}
                            <div class="col-lg-3 col-md-4 col-xs-6">
                                <div class="portfolio-item animate-on-scroll-init tw-relative">
                                    {% if portfolio_item.front_image %}
                                        <img src="{{ portfolio_item.front_image.url }}" class="img-res"
                                         alt="{{ portfolio_item.title }} Image">
                                    {% endif %}
                                    <div class="tw-absolute tw-bottom-2 tw-right-2 sm:tw-hidden tw-bg-black tw-bg-opacity-25 tw-p-4 tw-rounded-xl">
                                        <a href="{% url 'home:portfolio_item' pk=portfolio_item.id %}" class="tw-text-white">
                                            {{ portfolio_item.title }} <i class="fa fa-arrow-right" aria-hidden="true"></i>
                                        </a>
                                    </div>
                                    <h4 class="portfolio-item-title tw-hidden sm:tw-block">{{ portfolio_item.title }}</h4>
                                    <a class="tw-hidden sm:tw-block" href="{% url 'home:portfolio_item' pk=portfolio_item.id %}">
                                        <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
                                </div><!-- /.portfolio-item -->
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
            <div class="tw-flex tw-justify-center tw-items-center" >
                <a href="{% url 'home:portfolio' %}" id="moreProjectsBtn"  class="btn btn-border tw-my-14 animate-on-scroll-init">More Projects</a>
            </div>
            </div>
        </section><!-- /.section-portfolio -->
        <div class="parallax-bline"></div>

    </main><!-- /#main -->
{#    <script>#}
{#    </script>#}
{% endblock %}

templates/home/portfolio-item.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div id="hero" class="hero overlay subpage-hero portfolio-hero">
        <div class="hero-content">
            <div class="hero-text">
		{% if portfolio_item %}
			{% for item in portfolio_item %}
		                <h1>{{ item.title }}</h1>
			{% endfor %}
		{% endif %}
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{% url 'home:index' %}">Home</a></li>
                  <li class="breadcrumb-item"><a href="{% url 'home:portfolio' %}">Portfolio</a></li>
                    {% if portfolio_item %}
                        {% for item in portfolio_item %}
                  <li class="breadcrumb-item active">{{ item.title }}</li>
                        {% endfor %}
                    {% endif %}
                </ol>
            </div><!-- /.hero-text -->
        </div><!-- /.hero-content -->
    </div><!-- /.hero -->

    <main id="main" class="site-main">

        {% if portfolio_item %}
            {% for item in portfolio_item %}
        <section class="site-section subpage-site-section section-project">
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        {% if item.img_1 %}
                        <div class="project-img">
                            <img src="{{ item.img_1.url }}" class="img-portfolio-item" alt="">
                        </div>
                        {% endif %}
                        {% if item.img_2 %}
                        <div class="project-img">
                            <img src="{{ item.img_2.url }}" class="img-portfolio-item" alt="">
                        </div>
                        {% endif %}
                        {% if item.img_3 %}
                        <div class="project-img">
                            <img src="{{ item.img_3.url }}" class="img-portfolio-item" alt="">
                        </div>
                        {% endif %}
                        {% if item.img_4 %}
                        <div class="project-img">
                            <img src="{{ item.img_4.url }}" class="img-portfolio-item" alt="">
                        </div>
                        {% endif %}
                        {% if item.img_5 %}
                        <div class="project-img">
                            <img src="{{ item.img_5.url }}" class="img-portfolio-item" alt="">
                        </div>
                        {% endif %}
                    </div>
                    <aside class="col-md-4">
                        <div class="">
                            <h5>{{ item.title }}</h5>
                            <div class="project-date-y">
                                {% if item.date %}
                                    <p><span>Date:</span> {{ item.date }}</p>
                                {% endif %}
                                <p><span>Category:</span> {{ item.service_category }}</p>
                            </div>
                            {% if item.description_1 %}
                                <div class="">{{ item.description_1 | safe}}</div>
                            {% endif %}
                            {% if item.description_2 %}
                                <div class="">{{ item.description_2 | safe}}</div>
                            {% endif %}
                            {% if item.description_3 %}
                                <div class="">{{ item.description_3 | safe}}</div>
                            {% endif %}
                            {% if item.press_link %}
                                <a href="{{ item.press_link }}" class="btn btn-border mb-10">Press Coverage</a>
                            {% endif %}
                            {% if item.fb_link or item.ig_link or item.twitter_link or item.linkedin_link or item.spotify_link%}
                                <div class="project-date-category">
                                <p><span>Social Media Coverage:</span></p>
                                    <div class="social-links">
                                        {% if item.spotify_link %}
                                        <a class="spotify-bg" href="{{ item.spotify }}"><i class="fa fa-spotify"></i></a>
                                        {% endif %}
                                        {% if item.twitter_link %}
                                        <a class="twitter-bg" href="{{ item.twitter_link }}"><i class="fa fa-twitter"></i></a>
                                        {% endif %}
                                        {% if item.ig_link %}
                                        <a class="instagram" href="{{ item.ig_link }}"><i class="fa fa-instagram"></i></a>
                                        {% endif %}
                                        {% if item.fb_link %}
                                        <a class="facebook-bg" href="{{ item.fb_link }}"><i class="fa fa-facebook"></i></a>
                                        {% endif %}
                                        {% if item.linkedin_link %}
                                        <a class="linkedin-bg" href="{{ item.linkedin_link }}"><i class="fa fa-linkedin"></i></a>
                                        {% endif %}
                                    </div><!-- /.social-links -->
                                </div>
                            {% endif %}
                            
                        </div><!-- /.project-description -->
                    </aside>
                </div>
            </div>
        </section><!-- /.section-project -->
            {% endfor %}
        {% endif %}


        <section class="site-section subpage-site-section section-related-projects">
            <div class="container">
                {% if related_projects %}
                <div class="text-left">
                    <h2>Related Projects</h2>
                </div>
                    {% for project in related_projects %}
                        <div class="column">
                            <div class="col-lg-3 col-md-4 col-xs-6">
                                <div class="portfolio-item">
                                    {% if project.front_image %}
                                        <img src="{{ project.front_image.url }}" class="img-res" alt="{{ project.title }} Image">
                                    {% endif %}
                                    <div class="tw-absolute tw-bottom-2 tw-right-2 sm:tw-hidden tw-bg-black tw-bg-opacity-25 tw-p-4 tw-rounded-xl">
                                        <a href="{% url 'home:portfolio_item' pk=project.id %}" class="tw-text-white">
                                            {{ project.title }} <i class="fa fa-arrow-right" aria-hidden="true"></i>
                                        </a>
                                    </div>
                                    <h4 class="portfolio-item-title tw-hidden sm:tw-block">{{ project.title }}</h4>
                                    <a class="tw-hidden sm:tw-block" href="{% url 'home:portfolio_item' pk=project.id %}">
                                        <i class="fa fa-arrow-right" aria-hidden="true"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                        
                    {% endfor %}
                {% endif %}
            </div>
        </section>

    </main>
{% endblock %}

templates/home/portfolio.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div id="hero" class="hero overlay subpage-hero portfolio-hero">
        <div class="hero-content">
            <div class="hero-text">
                <h1>Our Impact</h1>
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{% url 'home:index' %}">Home</a></li>
                  <li class="breadcrumb-item active">Impact</li>
                </ol>
            </div><!-- /.hero-text -->
        </div><!-- /.hero-content -->
    </div><!-- /.hero -->
    {% if portfolio_items %}
    <main id="main" class="site-main">
        <section class="site-section subpage-site-section section-portfolio">
            <div class="container">
                <ul class="portfolio-sorting list-inline text-center">
                {% if unique_services %}
                        <li><a href="#" class="btn btn-border active" data-group="all">All</a></li>
                    {% for service in unique_services %}
                        <li><a href="#" class="btn btn-border" data-group="{{ service }}"><span class="px:5">{{ service }}</span></a></li>
                    {% endfor %}
                {% endif %}
                </ul><!-- /.portfolio-sorting  -->
                <div id="grid" class="row">
                    {% if portfolio_items %}
                        {% for portfolio_item in portfolio_items %}
                            <div class="col-lg-3 col-md-4 col-xs-6" data-groups='["{{ portfolio_item.service_category }}"]'>
                                <div class="portfolio-item animate-on-scroll-init tw-relative">
                                    {% if portfolio_item.front_image %}
                                        <img src="{{ portfolio_item.front_image.url }}" class="img-res"
                                         alt="{{ portfolio_item.title }} Image">
                                    {% endif %}
                                    <div class="tw-absolute tw-bottom-2 tw-right-2 sm:tw-hidden tw-bg-black tw-bg-opacity-25 tw-p-4 tw-rounded-xl">
                                        <a href="{% url 'home:portfolio_item' pk=portfolio_item.id %}" class="tw-text-white">
                                            {{ portfolio_item.title }} <i class="fa fa-arrow-right" aria-hidden="true"></i>
                                        </a>
                                    </div>
                                    <h4 class="portfolio-item-title tw-hidden sm:tw-block">{{ portfolio_item.title }}</h4>
                                    <a class="tw-hidden sm:tw-block" href="{% url 'home:portfolio_item' pk=portfolio_item.id %}">
                                        <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
                                </div><!-- /.portfolio-item -->
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
{#                <div class="text-center">#}
{#                    <a class="btn btn-border mb-10" href="#" id="loadMore">Load More</a>#}
{#                </div>#}
            </div>
        </section><!-- /.section-portfolio -->
    </main><!-- /#main -->
    {% endif %}
{% endblock %}