emb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home'))
]

home/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about_us, name='about'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('portfolio/portfolio-item/<int:pk>', views.portfolio_item, name='portfolio_item'),
    path('services/', views.services, name='services'),
]

urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Basic Page Needs
    ================================================== -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>KTAgency</title>

    <meta name="description" content="">
    <meta name="keywords" content="">

    <!-- Mobile Specific Metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,600,700" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">

    <!-- Favicon
    ================================================== -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon/favicon-16x16.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon/favicon-32x32.png' %}">


    <!-- Stylesheets
    ================================================== -->
    <!-- Tailwind  CSS -->
    <link rel="stylesheet" href="{% static 'css/output.css' %}">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <header id="masthead" class="site-header">
        <nav id="primary-navigation" class="site-navigation">
            <div class="container">
                <div class="navbar-header">
                    <a href="{% url 'home:index' %}" class="site-title"><span>KT</span>Agency</a>
                </div><!-- /.navbar-header -->
                <div class="collapse navbar-collapse" id="agency-navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li {% if  active_page == 'index' %} class="active" {% endif %}>
                            <a href="{% url 'home:index' %}">Home</a></li>
                        <!--
                        <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Pages<i class="fa fa-caret-down hidden-xs" aria-hidden="true"></i></a>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                              <li><a href="portfolio.html">Portfolio</a></li>
                              <li><a href="blog.html">Blog</a></li>
                            </ul>
                        </li>
                        -->
                        <li {% if  active_page == 'about' %} class="active" {% endif %}>
                            <a href="{% url 'home:about' %}">Our Story</a></li>
                        <li {% if  active_page == 'services' %} class="active" {% endif %}>
                            <a href="{% url 'home:services' %}">Our Solutions</a></li>
                        <li {% if  active_page == 'portfolio' %} class="active" {% endif %}
                        ><a href="{% url 'home:portfolio' %}">Our Impact</a></li>
                        <li><a class="contact-header-link" href="{% url 'home:services' %}#inquiry_form">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav><!-- /.site-navigation -->
    </header><!-- /#mastheaed -->
    {% block content %}


    {% endblock %}
    <footer class="tw-pt-28 sm:tw-pt-32 tw-bg-black">
        <div class="tw-mx-auto tw-w-11/12 tw-overflow-hidden tw-px-4 tw-py-20 sm:tw-py-24 lg:tw-px-8">
            <div class="tw-flex tw-flex-col md:tw-flex-row tw-justify-between">
                {% if content.address %}
                    {% if content.city_country %}
                        <div>
                            <h3 class="tw-border-l tw-border-indigo-600 tw-pl-6 tw-font-semibold tw-text-white">Address</h3>
                            <address class="tw-border-l tw-border-gray-200 tw-pl-6 tw-pt-2 tw-not-italic tw-text-gray-600">
                                {% if content.address %}
                                    <p>{{ content.address }},</p>
                                {% endif %}
                                {% if content.city_country %}
                                    <p>{{ content.city_country }}</p>
                                {% endif %}
                            </address>
                        </div>
                    {% endif %}
                {% endif %}
{#                <div>#}
{#                    <h3 class="tw-border-l tw-border-indigo-600 tw-pl-6 tw-font-semibold tw-text-white">Something Else</h3>#}
{#                    <address class="tw-border-l tw-border-gray-200 tw-pl-6 tw-pt-2 tw-not-italic tw-text-gray-600">#}
{#                        <p>We people apologise to people</p>#}
{#                    </address>#}
{#                </div>#}
                <div id="contact">
                    <h3 class="tw-border-l tw-border-indigo-600 tw-pl-6 tw-font-semibold tw-text-white didot-font">Contact Info</h3>
                    <div  class="tw-text-white tw-border-l tw-border-gray-200 tw-pl-6">
                        <p class="tw-flex tw-flex-row tw-justify-between">
                            <span class="tw-px-2">Email: </span>
                            <a href="mailto:{{ content.email }}">{{ content.email }}</a>
                        </p>
                        {% if content.phone_1 %}       
                            <p class="tw-flex tw-flex-row tw-justify-between">
                                <span>Tel:</span>
                                <span><a href="tel:{{ content.phone_1 }}">{{ content.phone_1 }}</a></span>
                            </p>
                        {% endif %}
                        {% if content.phone_1 %}       
                            <p class="tw-flex tw-flex-row tw-justify-between">
                                <span>Tel:</span>
                                <span><a href="tel:{{ content.phone_2 }}">{{ content.phone_2 }}</a></span>
                            </p>
                        {% endif %}
                    </div>
                </div>
            </div>
{#            <div class="tw-mt-16 tw-flex tw-justify-center tw-gap-x-10">#}
{#                <a href="" class="tw-text-white hover:tw-text-gray-800">#}
{#                    <span class="tw-sr-only">Some stuff</span>#}
{#                </a>#}
{#            </div>#}
            <div class="tw-mt-16 tw-border-t tw-border-white/10 tw-pt-8 sm:tw-mt-20 md:tw-flex md:tw-items-center md:tw-justify-between lg:tw-mt-24">
                <div class="tw-flex tw-gap-x-6 md:tw-order-2">
                    {% if content.twitter_link %}
                        <a class="tw-text-gray-400 hover:tw-text-gray-300" target="_blank" href="{{ content.twitter_link }}">
                            <span class="tw-sr-only">X</span>
                            <svg class="tw-size-8" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                                <path d="M13.6823 10.6218L20.2391 3H18.6854L12.9921 9.61788L8.44486 3H3.2002L10.0765 13.0074L3.2002 21H4.75404L10.7663 14.0113L15.5685 21H20.8131L13.6819 10.6218H13.6823ZM11.5541 13.0956L10.8574 12.0991L5.31391 4.16971H7.70053L12.1742 10.5689L12.8709 11.5655L18.6861 19.8835H16.2995L11.5541 13.096V13.0956Z"></path>
                            </svg>
                        </a>
                    {% endif %}
                    {% if content.fb_link %}
                        <a class="tw-text-gray-400 hover:tw-text-gray-300" target="_blank" href="{{ content.fb_link }}">
                            <span class="tw-sr-only">Facebook</span>
                            <svg class="tw-size-8" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                                <path fill-rule="evenodd" d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z" clip-rule="evenodd"></path>
                            </svg>
                        </a>
                    {% endif %}
                    {% if content.ig_link %}
                        <a class="tw-text-gray-400 hover:tw-text-gray-300" target="_blank" href="{{ content.ig_link }}">
                            <span class="tw-sr-only">Instagram</span>
                            <svg class="tw-size-8" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                                <path fill-rule="evenodd" d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z" clip-rule="evenodd"></path>
                            </svg>
                        </a>
                    {% endif %}
                    {% if content.linkedin_link %}
                        <a class="tw-text-gray-400 hover:tw-text-gray-300" target="_blank" href="{{ content.linkedin_link }}">
                            <span class="tw-sr-only">LinkedIn</span>
                            <i class="fa fa-lg fa-linkedin"></i>
                        </a>
                    {% endif %}
                </div>
                <p class="mt-8 text-sm/6 text-gray-400 md:order-1 md:mt-0">&copy; 2024 Kane Tower Agency, Inc. All rights reserved.</p>
            </div>
        </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'tinymce/tinymce.min.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
    <script src="{% static 'js/jquery.countTo.min.js' %}"></script>
    <script src="{% static 'js/jquery.shuffle.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>

</body>
</html>